Added VM restart to qui-domains
QubesOS/qubes-desktop-linux-manager pull request #106
Opened 2021-01-20 14:32 UTC by marmarta

A bit hacky, because Gtk really didn't want a big blocking function in
its loop, but it works.

fixes QubesOS/qubes-issues#6249

2021-03-11 15:46 UTC, marmarek requested changes

2021-03-11 15:46 UTC, marmarek commented on qui/tray/domains.py
> +        except exc.QubesException as ex:
Since you call `qvm-start` as a subprocess, it will be `CalledProcessError` on start, plus you need to capture stderr to get an actual message.

2021-04-11 23:32 UTC, ejose19 commented
Here's the adjusted `perform_restart` with @marmarek comments, feel free to integrate into your PR so this can be merged.

```python
async def perform_restart(self):
  try:
    self.vm.shutdown()
    while self.vm.is_running():
      await asyncio.sleep(1)
    pipe = subprocess.Popen(['qvm-start', self.vm.name], stderr=subprocess.PIPE)
    res = pipe.communicate()
    if (pipe.returncode != 0):
      raise exc.QubesException(res[1])
  except exc.QubesException as ex:
    show_error(_("Error restarting qube"),
               _("The following error occurred on an attempt to "
               "restart qube {0}:\n{1}").format(
                   self.vm.name, str(ex)))
```

2021-05-30 02:06 UTC, marmarek approved these changes

2021-05-30 02:07 UTC, merged