Explicitly state dependency on gnome-icon-theme
QubesOS/qubes-desktop-linux-manager pull request #136
Opened 2022-09-30 15:54 UTC by marmarta

fixes QubesOS/qubes-issues#7082

2022-10-03 12:57 UTC, marmarta commented
PipelineRetry

2022-10-03 14:21 UTC, marmarta commented
PipelineRetry

2022-10-18 12:23 UTC, marmarek requested changes

2022-10-18 12:23 UTC, marmarek commented on qui/decorators.py
> +            pixbuf = Gtk.IconTheme.get_default().load_icon(icon_name, 16, 0)
If both are present, then it will use -symbolic one. Is that intentional? If not, add `break` here.

2022-10-18 14:26 UTC, marmarek approved these changes

2022-10-18 14:27 UTC, merged