Actually run updater tests in CI
QubesOS/qubes-desktop-linux-manager pull request #193
Opened 2024-05-10 19:03 UTC by marmarta

Also, fix some updater tests that changed in the meantime.

2024-05-10 19:04 UTC, marmarta commented
@piotrbartman, those are the tests I mentioned - in particular there is one I marked as xfail, because I failed to figure out how to fix it, I'm guessing you might be better at it.

2024-05-14 03:16 UTC, marmarek requested changes

2024-05-14 03:16 UTC, marmarek commented on qui/eol.json
> +"fedora-37": "2024-12-23",
Should be 2023...

2024-05-16 13:09 UTC, marmarta commented
Ok but adding a gajillion tests and having 100% of diff coverage should not lead to codecov failing...... :(

2024-05-16 23:33 UTC, marmarek approved these changes

2024-05-17 00:00 UTC, merged