device identity
QubesOS/qubes-desktop-linux-manager pull request #217
Opened 2024-08-20 23:06 UTC by piotrbartman

implements QubesOS/qubes-issues/issues/9325

2024-08-26 23:05 UTC, piotrbartman commented
only dependency (`qubesadmin`) related errors left

2024-09-16 14:23 UTC, marmarta requested changes
I will also today test it on a test laptop for a more meaningful comments on the UI

2024-09-16 14:23 UTC, marmarta commented on qui/devices/backend.py
> +            assignment = DeviceAssignment(VirtualDevice(Port(
I think this needs a bit better documentation - this is a pretty opaque way of making a device assignment and a comment would be nice here :)

2024-09-16 14:23 UTC, marmarta commented on qui/devices/device_widget.py
> +                    changed_devices[str(device.port)] = backend.Device(
if the variable changed_devices is now a dict that maps port to device, that should be reflected in the name or at least in comments

2024-09-16 14:23 UTC, marmarta commented on qui/devices/device_widget.py
> +                        self.devices[str(device.port)] = backend.Device(
same here - it's very non-obvious that devices are indexed by port

2024-09-17 13:44 UTC, marmarta commented
So, I found a double bug. To reproduce: 
- install all packages relevant to this
- reboot
- make a device
- `qvm-device block assign --ask d12test f40xfce:loop0`
- try to start d12test

Result:
- I wait endlessly, nothing is happening (I think the daemon to show question failed to start?)
- worse, everything that uses qubes events hangs (qui-*, qvm-ls, everything) - something that should be async is not async?

2024-11-17 01:01 UTC, marmarek approved these changes

2024-11-17 03:27 UTC, merged