Fix markup injection issues
QubesOS/qubes-desktop-linux-manager pull request #236
Opened 2024-12-08 23:42 UTC by DemiMarie

This fixes some (theoretical) markup injection problems.  I believe none of the strings that I escape here will ever contain "<" or "&", but it is always safer to escape.

2024-12-11 13:18 UTC, marmarta commented
merge conflict, otherwise looks fine (but let's tests check it too)

2024-12-14 03:54 UTC, marmarek commented on qui/utils.py
> +    # pylint: disable=unidiomatic-typecheck
pylint was right here, use isinstance()

2024-12-14 03:58 UTC, marmarek commented on qui/tray/updates.py
> +            self.tray_menu.append(TextItem("Qube updates available!"))
Better apply `_()` to the string constant (tools extracting strings for translation will be happier).

2024-12-16 00:16 UTC, marmarek commented
FWIW openQA says:
```
Dec 15 19:01:36.069179 dom0 widget-wrapper[3495]: Traceback (most recent call last):
Dec 15 19:01:36.070033 dom0 widget-wrapper[3495]:   File "/usr/lib/python3.13/site-packages/qui/tray/disk_space.py", line 435, in make_menu
Dec 15 19:01:36.070033 dom0 widget-wrapper[3495]:     menu.append(self.make_title_item('Volumes'))
Dec 15 19:01:36.070033 dom0 widget-wrapper[3495]:                 ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
Dec 15 19:01:36.070033 dom0 widget-wrapper[3495]:   File "/usr/lib/python3.13/site-packages/qui/tray/disk_space.py", line 474, in make_title_item
Dec 15 19:01:36.070033 dom0 widget-wrapper[3495]:     label.set_markup("<b>{}</b>").format(GLib.markup_escape_text(text))
Dec 15 19:01:36.070033 dom0 widget-wrapper[3495]:     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 15 19:01:36.070033 dom0 widget-wrapper[3495]: AttributeError: 'NoneType' object has no attribute 'format'
```

2024-12-31 03:49 UTC, marmarek commented
Both pylint and tests detected some issues, I think the same one.

2025-01-03 04:19 UTC, marmarek commented
This will need rebase on top of #240 (queued for merging already).

2025-01-05 12:02 UTC, marmarek commented
openQA says:
```
Jan 05 00:05:36 dom0 qui-domains[3238]: Failed to set text '<markup><span color="{colormap[state]}">sys-whonix</span></markup>' from markup due to error parsing markup: Value of 'foreground' attribute on <span> tag on line 1 could not be parsed; should be a color specification, not '{colormap[state]}'
```

(there may be more issues like this)

2025-01-06 11:47 UTC, marmarek commented
> [Make the widgets work in KDE Wayland session](https://github.com/QubesOS/qubes-desktop-linux-manager/pull/236/commits/e011e5f9a6966a8a8e82502e28c820b01532ff05)

Mixed up PRs ?

2025-01-08 00:40 UTC, DemiMarie commented
> And that's all what openQA plus some manual testing found.

My test box uses KDE+Wayland, so this change was to make the code easier to test.  I’ll revert it.

2025-01-08 21:08 UTC, marmarta approved these changes
I thought there are more pressing concerns with gui stuff that you should be working on (how are tray icons coming from other VMs going?) than "theoretical injection issues", but sure, go ahead.

2025-01-08 21:13 UTC, marmarta commented
Ah, one more thing: add some unit test(s) to the function, codecov complains.

2025-01-08 21:22 UTC, marmarta requested changes
Please add some unit tests, codecov complains. I'm not sure if this is needed (see: theoretical), and I think your time could be better spent on things like fixing tray icons from non-dom0 VMs under wayland, but sure, we can have this.

2025-01-08 23:28 UTC, DemiMarie commented
Yeah, tray icons without menus are not a sufficient implementation no matter how much easier they are to implement.

2025-07-05 01:16 UTC, closed without merging